name: Docker CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t actuallytyara/php-dtp:latest .

    - name: Login DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker Image
      if: github.ref == 'refs/heads/main'
      run: docker push actuallytyara/php-dtp:latest
